# server/chains/retrieval_chain.py

import os
import logging
from datetime import datetime

from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain_chroma import Chroma
from langchain_text_splitters import RecursiveCharacterTextSplitter

from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import RunnableMap, RunnableLambda
from langchain_core.output_parsers import StrOutputParser
from operator import itemgetter

logger = logging.getLogger(__name__)

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")
CHROMA_DIR = os.path.join(DATA_DIR, "chroma")

# Lazy initialization of embedding model (only when needed, after API key is set)
_EMBED_MODEL = None

def get_embed_model():
    """Get or create the embedding model (lazy initialization)."""
    global _EMBED_MODEL
    if _EMBED_MODEL is None:
        # Check if API key is set
        if not os.getenv("OPENAI_API_KEY"):
            raise ValueError("OPENAI_API_KEY must be set before using embeddings")
        _EMBED_MODEL = OpenAIEmbeddings(model="text-embedding-3-small")
    return _EMBED_MODEL


# ============================================================
# 1) INGEST RESUME + JOB DOCUMENTS
# ============================================================
def ingest_docs() -> None:
    """
    Clears old vector DB, then ingests:
      - resume.txt
      - job.txt
      - autogenerated resume summary
    """
    os.makedirs(DATA_DIR, exist_ok=True)

    # Clear vector store
    import shutil
    if os.path.exists(CHROMA_DIR):
        shutil.rmtree(CHROMA_DIR)
    os.makedirs(CHROMA_DIR, exist_ok=True)

    chroma = Chroma(embedding_function=get_embed_model(), persist_directory=CHROMA_DIR)
    splitter = RecursiveCharacterTextSplitter(chunk_size=800, chunk_overlap=300)

    docs = []

    # Ingest resume
    resume_path = os.path.join(DATA_DIR, "resume.txt")
    resume_summary = None

    if os.path.exists(resume_path):
        with open(resume_path, "r", encoding="utf-8") as f:
            text = f.read().strip()

        if text:
            resume_summary = _extract_resume_summary(text)

            # Chunk full resume
            for chunk in splitter.create_documents([text]):
                chunk.metadata = {
                    "source": "resume",
                    "type": "resume",
                }
                docs.append(chunk)

            # Add structured summary chunk
            if resume_summary:
                from langchain_core.documents import Document

                docs.append(
                    Document(
                        page_content=f"RESUME SUMMARY:\n{resume_summary}",
                        metadata={"source": "resume_summary", "type": "summary"}
                    )
                )

    # Ingest job description
    job_path = os.path.join(DATA_DIR, "job.txt")
    if os.path.exists(job_path):
        with open(job_path, "r", encoding="utf-8") as f:
            text = f.read().strip()
        if text:
            for chunk in splitter.create_documents([text]):
                chunk.metadata = {"source": "job", "type": "job"}
                docs.append(chunk)

    if not docs:
        logger.warning("⚠ No resume/job documents found during ingestion.")
        return

    chroma.add_documents(docs)
    logger.info(f"✅ Ingestion complete ({len(docs)} chunks)")


# ============================================================
# 2) APPEND TRANSCRIPT CHUNK (REAL-TIME INGESTION)
# ============================================================
def append_transcript_chunk(text: str, speaker: str = "unknown", timestamp: str = None):
    """
    Appends a single real-time transcript chunk into the vector DB.
    Called every time STT returns text.
    """
    if not text or not text.strip():
        return False

    timestamp = timestamp or str(datetime.now())
    chroma = Chroma(embedding_function=get_embed_model(), persist_directory=CHROMA_DIR)

    splitter = RecursiveCharacterTextSplitter(chunk_size=350, chunk_overlap=50)
    chunks = splitter.create_documents([text])

    for c in chunks:
        c.metadata = {
            "type": "transcript",
            "speaker": speaker,
            "timestamp": timestamp
        }

    chroma.add_documents(chunks)

    logger.info(f"📝 Added transcript chunk ({len(chunks)} pieces)")
    return True


# ============================================================
# 3) BUILD BASIC RETRIEVAL CHAIN (Legacy)
# ============================================================
def build_chain():
    """
    Original retrieval chain used for /generate (non-stream).
    Now supports searching full vector DB (resume + job + transcript).
    """
    if not os.path.exists(CHROMA_DIR):
        raise ValueError("Vector store missing — run /ingest first.")

    chroma = Chroma(embedding_function=get_embed_model(), persist_directory=CHROMA_DIR)
    retriever = chroma.as_retriever(search_kwargs={"k": 6})

    llm = ChatOpenAI(model="gpt-4o", temperature=0.3)

    prompt = PromptTemplate(
        input_variables=["context", "question", "chat_history"],
        template="""
You are an expert interview answer assistant.

### CONTEXT (Resume + Job + Transcript):
{context}

### Previous conversation:
{chat_history}

### Interview Question:
{question}

Generate a clear, natural 2–4 sentence answer using:
- the transcript context (conversation with HR)
- the resume experience
- relevant job requirements
""",
    )

    chain = (
        RunnableMap({
            "context": itemgetter("question") | retriever,
            "question": itemgetter("question"),
            "chat_history": itemgetter("chat_history"),
        })
        | prompt
        | llm
        | StrOutputParser()
    )

    chain = chain | RunnableLambda(lambda t: {"answer": t})
    logger.info("✅ Retrieval chain ready (resume + job + transcript)")
    return chain


# ============================================================
# 4) OPTIONAL: SIMPLE RETRIEVER
# ============================================================
def build_retriever(k: int = 5):
    """Provide a raw retriever."""
    if not os.path.exists(CHROMA_DIR):
        raise ValueError("Vector store missing — run /ingest first.")

    chroma = Chroma(embedding_function=get_embed_model(), persist_directory=CHROMA_DIR)
    return chroma.as_retriever(search_kwargs={"k": k})


# ============================================================
# 5) HELPER: RESUME SUMMARY EXTRACTOR
# ============================================================
def _extract_resume_summary(resume_text: str) -> str:
    """
    Extract structured summary using GPT-4o.
    """
    try:
        llm = ChatOpenAI(model="gpt-4o", temperature=0.1)
        prompt = PromptTemplate(
            input_variables=["resume"],
            template="""Extract detailed structured resume info.

Resume:
{resume}

Return a structured summary including:
- personal info
- experience
- skills
- projects
- education
""",
        )
        chain = prompt | llm
        out = chain.invoke({"resume": resume_text})
        return out.content if hasattr(out, "content") else str(out)

    except Exception as e:
        logger.warning("⚠ Resume summary extraction failed:", e)
        return resume_text[:400]
